# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 00:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name_plural': 'Mapas',
                'verbose_name': 'Mapa',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=255, verbose_name='Origem')),
                ('destiy', models.CharField(max_length=255, verbose_name='Destino')),
                ('distance', models.PositiveSmallIntegerField(verbose_name='Distancia em km')),
                ('map_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='api.Map', verbose_name='Mapa')),
            ],
            options={
                'ordering': ['map_name'],
                'verbose_name_plural': 'Rotas',
                'verbose_name': 'Rota',
            },
        ),
    ]
