# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 00:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='destiy',
            new_name='destiny',
        ),
    ]
